# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import identity_pb2 as identity__pb2


class IdentityStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getIdentity = channel.unary_unary(
        '/iota.Identity/getIdentity',
        request_serializer=identity__pb2.IdentityIdOnly.SerializeToString,
        response_deserializer=identity__pb2.IdentityOnly.FromString,
        )
    self.insert = channel.unary_unary(
        '/iota.Identity/insert',
        request_serializer=identity__pb2.IdentityOnly.SerializeToString,
        response_deserializer=identity__pb2.IdentityOnly.FromString,
        )
    self.validate = channel.unary_unary(
        '/iota.Identity/validate',
        request_serializer=identity__pb2.IdentityRoot.SerializeToString,
        response_deserializer=identity__pb2.IdentityValidate.FromString,
        )


class IdentityServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getIdentity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def insert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def validate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IdentityServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getIdentity': grpc.unary_unary_rpc_method_handler(
          servicer.getIdentity,
          request_deserializer=identity__pb2.IdentityIdOnly.FromString,
          response_serializer=identity__pb2.IdentityOnly.SerializeToString,
      ),
      'insert': grpc.unary_unary_rpc_method_handler(
          servicer.insert,
          request_deserializer=identity__pb2.IdentityOnly.FromString,
          response_serializer=identity__pb2.IdentityOnly.SerializeToString,
      ),
      'validate': grpc.unary_unary_rpc_method_handler(
          servicer.validate,
          request_deserializer=identity__pb2.IdentityRoot.FromString,
          response_serializer=identity__pb2.IdentityValidate.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iota.Identity', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
