# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='identity.proto',
  package='iota',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0eidentity.proto\x12\x04iota\"\x1e\n\x0eIdentityIdOnly\x12\x0c\n\x04root\x18\x01 \x01(\t\"*\n\x0cIdentityRoot\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\x12\x0c\n\x04root\x18\x02 \x01(\t\"\x1c\n\x0cIdentityOnly\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\"$\n\x10IdentityValidate\x12\x10\n\x08validate\x18\x01 \x01(\x08\x32\xb3\x01\n\x08Identity\x12\x39\n\x0bgetIdentity\x12\x14.iota.IdentityIdOnly\x1a\x12.iota.IdentityOnly\"\x00\x12\x32\n\x06insert\x12\x12.iota.IdentityOnly\x1a\x12.iota.IdentityOnly\"\x00\x12\x38\n\x08validate\x12\x12.iota.IdentityRoot\x1a\x16.iota.IdentityValidate\"\x00\x62\x06proto3'
)




_IDENTITYIDONLY = _descriptor.Descriptor(
  name='IdentityIdOnly',
  full_name='iota.IdentityIdOnly',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root', full_name='iota.IdentityIdOnly.root', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=54,
)


_IDENTITYROOT = _descriptor.Descriptor(
  name='IdentityRoot',
  full_name='iota.IdentityRoot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='iota.IdentityRoot.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root', full_name='iota.IdentityRoot.root', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=98,
)


_IDENTITYONLY = _descriptor.Descriptor(
  name='IdentityOnly',
  full_name='iota.IdentityOnly',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='iota.IdentityOnly.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=128,
)


_IDENTITYVALIDATE = _descriptor.Descriptor(
  name='IdentityValidate',
  full_name='iota.IdentityValidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='validate', full_name='iota.IdentityValidate.validate', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=166,
)

DESCRIPTOR.message_types_by_name['IdentityIdOnly'] = _IDENTITYIDONLY
DESCRIPTOR.message_types_by_name['IdentityRoot'] = _IDENTITYROOT
DESCRIPTOR.message_types_by_name['IdentityOnly'] = _IDENTITYONLY
DESCRIPTOR.message_types_by_name['IdentityValidate'] = _IDENTITYVALIDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdentityIdOnly = _reflection.GeneratedProtocolMessageType('IdentityIdOnly', (_message.Message,), {
  'DESCRIPTOR' : _IDENTITYIDONLY,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:iota.IdentityIdOnly)
  })
_sym_db.RegisterMessage(IdentityIdOnly)

IdentityRoot = _reflection.GeneratedProtocolMessageType('IdentityRoot', (_message.Message,), {
  'DESCRIPTOR' : _IDENTITYROOT,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:iota.IdentityRoot)
  })
_sym_db.RegisterMessage(IdentityRoot)

IdentityOnly = _reflection.GeneratedProtocolMessageType('IdentityOnly', (_message.Message,), {
  'DESCRIPTOR' : _IDENTITYONLY,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:iota.IdentityOnly)
  })
_sym_db.RegisterMessage(IdentityOnly)

IdentityValidate = _reflection.GeneratedProtocolMessageType('IdentityValidate', (_message.Message,), {
  'DESCRIPTOR' : _IDENTITYVALIDATE,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:iota.IdentityValidate)
  })
_sym_db.RegisterMessage(IdentityValidate)



_IDENTITY = _descriptor.ServiceDescriptor(
  name='Identity',
  full_name='iota.Identity',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=169,
  serialized_end=348,
  methods=[
  _descriptor.MethodDescriptor(
    name='getIdentity',
    full_name='iota.Identity.getIdentity',
    index=0,
    containing_service=None,
    input_type=_IDENTITYIDONLY,
    output_type=_IDENTITYONLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='insert',
    full_name='iota.Identity.insert',
    index=1,
    containing_service=None,
    input_type=_IDENTITYONLY,
    output_type=_IDENTITYONLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='validate',
    full_name='iota.Identity.validate',
    index=2,
    containing_service=None,
    input_type=_IDENTITYROOT,
    output_type=_IDENTITYVALIDATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IDENTITY)

DESCRIPTOR.services_by_name['Identity'] = _IDENTITY

# @@protoc_insertion_point(module_scope)
